version: '3.8'

networks:
  default:
    driver: bridge
    external: false

services:
  camrsti-mysql:
    image: mysql:8-debian
    container_name: camrsti-mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=camrsti
      - MYSQL_DATABASE=camrstidb
    volumes:
      - ./mysql/data:/var/lib/mysql
    # ports:
    #   - 3306:3306
  
  camrsti-back:
    build: ./back/
    image: ablocker/camrsti-back:latest
    container_name: camrsti-back
    restart: on-failure
    environment:
      - MYSQL_HOST=camrsti-mysql
    depends_on:
      - camrsti-mysql
    # ports:
    #   - 8081:8081
  
  camrsti-file:
    build: ./file/
    image: ablocker/camrsti-file:latest
    container_name: camrsti-file
    restart: on-failure
    volumes:
      - ./file/public:/camrsti-file/public
    # ports:
    #   - 8082:8082
  
  camrsti-front:
    build: ./front/
    image: ablocker/camrsti-front:latest
    container_name: camrsti-front
    restart: on-failure
    ports:
      - 8088:80
    depends_on:
      - camrsti-back
      - camrsti-image
